### ISSUE TITLE
The package depends on old click.

### ISSUE THREAD

**Issue by kovalp** [AstraZeneca/jazzy#207]
This makes difficult to use with recent kallisto or flask.

**Comment by f3rmion** [comment]
Hi @kovalp,

Thanks for bringing this up. I updated dependencies in #208.

**Comment by kovalp** [comment]
Thank you for looking at this. It would be nice to have the package it in the PyPI.

**Comment by f3rmion** [comment]
Hi @kovalp,

I created a maintenance release (v0.0.8), which is now also available on PyPI.

**Comment by ghiander** [comment]
Hello @kovalp,

Thanks for pointing this out. Please let us know if Jazzy behaves as expected so we can close this issue.

**Comment by kovalp** [comment]
> Hello @kovalp,
> 
> Thanks for pointing this out. Please let us know if Jazzy behaves as expected so we can close this issue.

It can take some time. I am trying to use jazzy in a hobby project. But, I think by Monday you will hear from me again.

**Comment by kovalp** [comment]
Works
