### ISSUE TITLE
Is it essential to restrict the version of click in jazzy?

### ISSUE THREAD

**Issue by kovalp** [AstraZeneca/jazzy#214]
I could add jazzy to my project. However, the `click` has been downgraded

`  • Updating click (8.1.3 -> 8.0.4)
`

Could it be possible to use the latest click in jazzy?

**Comment by f3rmion** [comment]
Hi,

We use [*poetry*](https://python-poetry.org/) to manage our dependencies. If you need another version of *click* feel free to clone the source code and adjust the [pyproject.toml](https://github.com/AstraZeneca/jazzy/blob/master/pyproject.toml#L22) according to your needs. Poetry will then make sure that the dependencies and sub-dependencies of the packages in your virtual environment are compatible with each other.

Cheers,
Eike
