### ISSUE TITLE
pickle module load

### ISSUE THREAD

**Issue by gpwood** [AstraZeneca/jazzy#224]
Hi!

I'm trying to follow some of the notebooks (guthrie_deltag_validation and gerber_deltag_validation) however, I'm getting an error when trying to unpickle one of the .pbz2 files. For example

```
import os
import sys
import bz2
import mpld3
import pandas as pd
import _pickle as cPickle
import svgutils.transform as sg
import matplotlib.pyplot as plt

from jazzy import core
from rdkit import Chem
from rdkit.Chem.Draw import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D
from sklearn.metrics import mean_absolute_error, r2_score
# from mpld3 import plugins
# mpld3.enable_notebook()
# Import config
opt_path = os.path.abspath(os.path.join(os.getcwd(), '..', 'optimisation'))
sys.path.insert(0, opt_path)
import config

# Open the study
data_path = os.path.abspath(os.path.join(os.getcwd(), '..', config.DATA_PATH))
optuna_path = os.path.join(data_path, config.OPTUNA_DIRNAME)
study_filepath = os.path.join(optuna_path, config.OPTUNA_DELTAG_STUDY_FILENAME)
study = bz2.BZ2File(study_filepath, 'rb')
study = cPickle.load(study)

best_params = study.best_trial.params
best_params
```

results in 

```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 11
      9 study_filepath = os.path.join(optuna_path, config.OPTUNA_DELTAG_STUDY_FILENAME)
     10 study = bz2.BZ2File(study_filepath, 'rb')
---> 11 study = cPickle.load(study)
     13 best_params = study.best_trial.params
     14 best_params

ModuleNotFoundError: No module named 'optuna._study_direction'
```

**Comment by ghiander** [comment]
Hello! Thanks for reaching out. That error comes from the accidental upgrade of `optuna` from version 2.3.0 to 3.1.0. If you force the downgrade of optuna, you'll be able to open the study file. Just use `pip install optuna==2.3.0` to execute the downgrade.

In the meantime, I'll push a fix for this and regenerate the best parameter file as a serialisable so there will be no need to have `optuna` installed.

**Comment by ghiander** [comment]
I pushed a fix for this so that you can load the parameters without sticking to a specific version of `optuna`: https://github.com/AstraZeneca/jazzy/commit/c365aedf44797667d8c0dd9356d57374fc357ec1

Your issue should be solved now.
