### ISSUE TITLE
Interpreting SDC/SDX values - are these on the same scale? 

### ISSUE THREAD

**Issue by ljmartin** [AstraZeneca/jazzy#228]
Hi Jazzy, thanks for making this great package available!

I'm having trouble interpreting the hydrogen bond acceptor/donor strengths. Are these all on the same scale? Reusing an [example from the docs](https://jazzy.readthedocs.io/en/latest/cookbook.html#hydrogen-bond-strength-depiction), I see that the hydrogen with the strongest donor strength is an aryl hydrogen, circled in orange below. Intuitively, this doesn't scan - the amide H and phenolic H should be higher, but maybe I'm interpreting this incorrectly. Are the SDC/SDX values calculated on the same scale?

code: 
```python
from IPython.display import SVG
from jazzy.api import atomic_strength_vis_from_smiles
SVG(atomic_strength_vis_from_smiles(smiles="CC(=O)NC1=CC=C(C=C1)O",
                                    flatten_molecule=True,
                                    highlight_atoms=True,
                                    ignore_sdc=False,
                                    ignore_sdx=False,
                                    ignore_sa=False,
                                    sdc_threshold=0.0,
                                    sdx_threshold=0.0,
                                    sa_threshold=0.0,
                                    #rounding_digits=2
                                   ))
```
<img width="532" alt="Screenshot 2023-03-22 at 8 39 36 am" src="https://user-images.githubusercontent.com/8262765/226747582-7e013ecd-6178-4758-908d-51374753ace5.png">

**Comment by ghiander** [comment]
Hello Lewis, yes they are on the same scale. We have also noticed some unexpected results sometimes when it comes to comparing C-H (SDC) and X-H (SDX) donors. I would suggest you minimise the energy of the geometry of your molecule before running the calculation though:

![image](https://user-images.githubusercontent.com/30413455/226853114-b764c415-ddab-4087-91f3-919cc176a9b5.png)

**Comment by ljmartin** [comment]
Thanks @ghiander for the tip! 
This does indeed adjust the donor strengths. I'll leave this open for now, since the highest SDC score (aryl H donor strength) is still greater than all the SDX scores (amide and phenolic donor strengths).

**Comment by ghiander** [comment]
Hello Lewis. Yes, as I said, we've also noticed some unexpected results but they are mathematically correct. It would be nice to verify what are the influences of the amide and the hydroxyl groups on that particularly strong hydrogen in the ring.

**Comment by ghiander** [comment]
Hello @ljmartin, how are you getting on with the testing? Can we close this issue?
