### ISSUE TITLE
SQLAlchemy included in Jazzy dependencies?

### ISSUE THREAD

**Issue by ghiander** [AstraZeneca/jazzy#229]
```
pip install jazzy
Collecting sqlalchemy>=1.1.0
  Downloading SQLAlchemy-2.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 2.1 MB/s eta 0:00:00
```

Why is this? Can we review and slim down?

**Comment by f3rmion** [comment]
It's not a direct dependency, so this must come in as a sub-dependency.
The first commit that introduced SQLAlchemy was [this here](https://github.com/AstraZeneca/jazzy/tree/29e7be96f3c5099c9f1b1ad27db0ca0b2f754d24)

**Comment by ghiander** [comment]
It's an `optuna` dependency: https://github.com/AstraZeneca/jazzy/blob/29e7be96f3c5099c9f1b1ad27db0ca0b2f754d24/poetry.lock#L589L605

We need to make sure that optuna is installed only optionally then. Need to play a bit with it. I'll close this issue.

**Comment by ghiander** [comment]
Solved by https://github.com/AstraZeneca/jazzy/pull/234
