### ISSUE TITLE
Update dependencies for compatibility in integration

### ISSUE THREAD

**Issue by ghiander** [AstraZeneca/jazzy#322]
**Is your feature request related to a problem? Please describe.**
ERROR: kallisto 1.0.9 has requirement scipy==1.9.2, but you'll have scipy 1.10.1 which is incompatible.
ERROR: jazzy 0.0.11 has requirement click==8.0.4, but you'll have click 8.1.7 which is incompatible.
ERROR: jazzy 0.0.11 has requirement rdkit<=2022.9.5, but you'll have rdkit 2023.3.3 which is incompatible.

**Describe the solution you'd like**
Release constraints and verify that the library is functioning as expected.

**Comment by f3rmion** [comment]
`kallisto` has been updated to get rid of fixed dependencies.
