### ISSUE TITLE
Empty string passed into deltag_from_smiles throws a ValueError rather than an JazzyError

### ISSUE THREAD

**Issue by JW-CINF** [AstraZeneca/jazzy#93]
Hi Jazzy devs, 

Great work on the library! I came across a possible small bug when testing the library. 

__*Summary*__ 

Passing an empty string into deltag_from_smiles leads to an ValueError rather than a JazzyError. This is likely because an empty string can be parsed as a blank graph by the RDKit. The catch in the rdkit_molecule_from_smiles checks for a None thus a blank molecule object can pass through leading to the ValueError being thrown in the corresponding embedmolecule step. 

__*Expected behaviour*__ 

The expected behaviour I imagine would be to have a catch on the possibility that an empty string or an empty molecule is parsed and then a JazzyError is thrown. 

__*Reproducibility steps*__
```python
from jazzy.api import deltag_from_smiles
deltag_from_smiles("")
```
__*Logs*__
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/anaconda3/envs/jazzy_test/lib/python3.8/site-packages/jazzy/api.py", line 106, in deltag_from_smiles
    rdkit_molecule, kallisto_molecule = __smiles_to_molecule_objects(
  File "/home/james/anaconda3/envs/jazzy_test/lib/python3.8/site-packages/jazzy/api.py", line 29, in __smiles_to_molecule_objects
    rdkit_mol = rdkit_molecule_from_smiles(
  File "/home/james/anaconda3/envs/jazzy_test/lib/python3.8/site-packages/jazzy/core.py", line 53, in rdkit_molecule_from_smiles
    emb_code = AllChem.EmbedMolecule(mh, randomSeed=11)
ValueError: molecule has no atoms
```

__*Testing environment*__

Ubuntu 20.04.4 LTS, Python 3.18.3, Jazzy 0.0.6

**Comment by f3rmion** [comment]
Hi @JW-CINF,

I reproduced this issue and agree that we should raise a JazzyError instead.
We address this issue soon- I'll then link the PR here.

Best,
Eike

**Comment by ghiander** [comment]
Fixed: [https://github.com/AstraZeneca/jazzy/pull/153](https://github.com/AstraZeneca/jazzy/pull/153). Thanks JW
